version: "3.8"
services:
  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}

  # postgres:
  #   container_name: postgres
  #   image: postgres
  #   restart: always
  #   ports:
  #     - "9999:5432"
  #   environment:
  #     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  #     - POSTGRES_DB=db
  #   volumes:
  #     - ./Databases:/var/lib/postgresql/data
